name: engagefire
description: Build apps faster with this quick firebase library
version: 0.1.0
authors:
  - James Brinkerhoff <james@devengage.io>
homepage: https://github.com/devengage/engagefire-dart

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  # googleapis_auth: ^0.2.3+5
  # http: ">=0.11.3 <0.13.0"
  # js: ^0.6.0
  # service_worker: ^0.2.0
  flutter:
    sdk: flutter

  firebase_core: ^0.3.4
  firebase_analytics: ^2.1.1+3

  cloud_firestore: ^0.10.1
  firebase_storage: ^2.1.1+2

  firebase_auth: ^0.8.4+5
  google_sign_in: ^4.0.1+1
  uuid: ^1.0.0
  http: ^0.12.0

  # files
  network_to_file_image: ^2.0.7
  image_crop: ^0.3.1
  image_picker: ^0.6.1+4
  file_picker: ^1.4.1

  # ads
  firebase_admob: ^0.9.0+7

  # firebase_dynamic_links 0.5.0+1
  # flutter_tags 0.4.3

dev_dependencies:
  # path: ^1.3.9
  # pedantic: ^1.3.0
  # test: ^1.6.0

  # build_runner: ^1.0.0
  # build_test: ^0.10.0
  # build_web_compilers: ^1.2.0
