name: engagefire
description: Build apps faster with this quick firebase library
version: 0.1.0
authors:
  - James Brinkerhoff <james@devengage.io>
homepage: https://github.com/devengage/engagefire-dart

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  # googleapis_auth: ^0.2.3+5
  # http: ">=0.11.3 <0.13.0"
  # js: ^0.6.0
  # service_worker: ^0.2.0
  flutter:
    sdk: flutter

  firebase_auth: ^0.15.0+1
  cloud_firestore: ^0.13.0+1
  cloud_firestore_all: ^0.1.1+4
  firebase_storage: ^3.0.8
  firebase_analytics: ^5.0.6
  # ads: ^1.2.0
  firebase_core: "^0.4.2+1"

  google_sign_in: ^4.0.14
  uuid: ^2.0.0
  http: ^0.12.0

  # files
  cached_network_image: ^2.0.0-rc.1
  image_crop: ^0.3.1
  image_picker: ^0.6.2+1
  file_picker: ^1.4.3+1

  provider: ^4.0.1

  rxdart: ^0.23.1

  # firebase_dynamic_links 0.5.0+1
  # flutter_tags 0.4.3

dev_dependencies:
  # path: ^1.3.9
  # pedantic: ^1.3.0
  # test: ^1.6.0

  # build_runner: ^1.0.0
  # build_test: ^0.10.0
  # build_web_compilers: ^1.2.0
